### PR TITLE
Improve notification e-mails

### PR DESCRIPTION
**Pull request by aleixpol**
Get the username in the subject
Condense some of the information

Context:
We've been using this in KDE, and it's been a bit hard for me to get used to the e-mails, I thought this can be a step forward.
One thing I wanted to do but didn't know how to do is to get the event name on the subject.

Feedback more than welcome.

### CODE REVIEW

**Comment by ancorgs** [comment]
I will take a look today, fixing the issues (see travis) and adding the event name

**Comment by aleixpol** [comment]
If you help me decode it, I can fix it too.

**Comment by ancorgs** [comment]
@aleixpol Well, I haven't tried, but this should fix it (and be a good tip for fixing similar problems).

```diff
--- a/app/mailers/has_state_mailer.rb
+++ b/app/mailers/has_state_mailer.rb
@@ -5,6 +5,14 @@ class HasStateMailer < ApplicationMailer
     @state_name = @machine.human_state_name
     @updated_at = @machine.state_updated_at
     @change = @machine.state_changes.newest_first.first
-    mail(:to => to,  :subject => t(:mailer_subject_state, :machine => @machine.title))
+    mail(:to => to,
+         :subject => t(:mailer_subject_state,
+                       :machine => @machine.title,
+                       :user => @machine.user.nickname,
+                       # With the current implementation the #try is not
+                       # required (Request and Reimbursement always respond to
+                       # #event), but better stay safe for future classes
+                       # performing "include HasState"
+                       :event => @machine.try(:event).try(:name)))
   end
 end

```

**Comment by ancorgs** [comment]
Thanks!

**Pull request merged**
