### PR TITLE
Added a doc for markdown support

### PR DESCRIPTION
**Pull request by nikhilgupta1211**

### CODE REVIEW

**Comment by ChrisBr** [comment]
Not sure if we really need a dedicated document for that. From my POV having the link implemented in #72 is enough documentation. @bgeuken what do you think?

**Comment by bgeuken** [comment]
@bgeuken I agree

**Comment by nikhilgupta1211** [comment]
So should I close this PR?

**Comment by bgeuken** [comment]
Yup, let's close it.

**Pull request closed without merging**
